version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: "cepapp-db"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: cepapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock-root:/home/wiremock
    container_name: "cepapp-mock"
volumes:
  db_data:
